GET http://localhost:1337/api/users/me?populate=role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgwMzI1MDM2LCJleHAiOjE3ODI5MTcwMzZ9.FUrDp9GNZtEAlhDaqH9RvFtwBGXBLb6p0C9L5mCpN9I